services:
  api:
    image: suneeln646/portfolio-api
    container_name: portfolio-api
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env

  ui:
    image: suneeln646/portfolio-ui
    container_name: portfolio-ui
    ports:
      - "3000:3000"
    env_file:
      - ./ui/.env.local
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl:/etc/ssl:ro
    depends_on:
      - ui
      - api
