name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push API
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-api ./api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-api

      - name: Build & Push UI
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-ui \
          --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} ./ui
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-ui
      - name: SSH into VPS and pull latest
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |

            PID=$(sudo lsof -t -i:80) || true
            if [ -n "$PID" ]; then
              echo "Stopping nginx..."
              sudo kill -9 $PID
            else
              echo "Nginx is not running."
            fi

            cd ${{ secrets.VPS_SSH_DEPLOYMENT_PATH }}
            docker system prune -af --volumes
            git pull origin main
            docker-compose pull
            docker-compose down --remove-orphans
            docker-compose up -d
